---
title: Milestone 1 Testing a Model for an Automated Real-Time Acuity Monitoring System in the Emergency Department
author:  
  - name: Tommy Flynn
    email: tjflynn@emory.edu
    affiliation: Emory University
    footnote: Corresponding Author
address:
    code: Emory University
    address: Emory University Nell Hodgson School of Nursing, 1520 Clifton Road NE, Atlanta, GA, 30322
abstract: The purpose of this project is to determine if patient acuity in the ED is correlated to patient eigenvector centrality in the network of all face to face ED interactions. 
  

bibliography: mybibfile.bib
output: rticles::elsevier_article
---


Overview & Motivation
=====================
- Overview and Motivation: Why did you undertake this particular project? What inspired you, what are your background and research interests that may have influenced your decision? 




As a ballpark, your proposal should be about 2-3 pages of text, along with shells of the tables and figures that you plan. You could even include some preliminary data acquisition / analysis steps.


Objectives
==========
- Project Objectives: What is the primary focal question that you are trying to answer? What would you like to learn and accomplish?

The purpose of this study is to test the accuracy of the Emergency Severity Index (ESI) as a metric used to predict patient needs. To test the accuracy of the ESI, this study uses radiofrequency identification (RFID) locating data that includes every interaction patients have with ED staff (nurses, techs, administrators, and providers) and the duration of each of those interactions. Using this data will require specific knowledge of the R statistical packages, network analysis, and data science. My learning objectives are to: 
```{r, echo=FALSE}
column_names <- c("Demonstrate effective use of GitHub Version Control", "Demonstrate working knowledge of R Studio & R Markdown", "Create useful visualizations of data", "Apply appropriate statistical methods", "Interpret statistical results")
row_names <- c("Action Items", "Timeline", "Outcome")
github <- c("Use GitHub version control throughout project development", "Ongoing", "Complete record of data management & analysis")
rstudio <- ("All data wrangling & analysis in R Studio and all milestones completed in R Markdown", "Ongoing", "Final Project, Presentation, and Website Completed in R Markdown")
visualize <- c("Apply appropriate packages for informative visualizations in R")

```
- Demonstrate proficiency with CRAN network analysis and visualization packages in R Studio
- Apply version control to version control with GitHub, and publication with R Markdown.
- Apply visualization tools to the data and results that create greater understanding of the research and significance.
- 

Data
====

- Data: from where and how are you acquiring your data? **Provide a link to your data source.**
##Data:

- Data Wrangling: Do you anticipate that there will be extensive data cleaning / reshaping / extraction? Are there questions you will need to calculate in your data (e.g., perhaps you have height and weight, but not BMI)? How will you implement this particular data wrangling step?
##Data Wrangling:

Analysis Plan
=============
- Exploratory Analysis: Which methods / visualizations are you planning to use to explore your tidy dataset?
##Exploratory Analysis


- Analysis: How are you planning to analyze your data?
##Analysis


- Schedule, keeping in mind the due dates listed above for the intermediate and final milestones, make a plan to meet these deadlines. Write these in terms of weekly tasks / goals.
##Schedule


Results
=======




Discussion
==========
Allocating staff resources in an Emergency Department is an ongoing challenge. 



Conclusion
==========





References {#references.unnumbered} 
==========

@Allaire2017

@CRAN

